language: python
sudo: false
dist: trusty
cache: pip

env:
  global:
    - PYTHONFAULTHANDLER=x
    - SKIP_LATEX_BUILD=1

matrix:
  include:
    - python: 'pypy'
      env: TOXENV=pypy
    - python: '2.7'
      env:
        - TOXENV=du13
        - PYTEST_ADDOPTS="--cov ./ --cov-append --cov-config setup.cfg"
    - python: '3.4'
      env: TOXENV=py34
    - python: '3.5'
      env: TOXENV=py35
    - python: '3.6'
      env:
        - TOXENV=py36
        - PYTEST_ADDOPTS="--cov ./ --cov-append --cov-config setup.cfg"
    - python: 'nightly'
      env: TOXENV=py37
    - python: '3.6'
      env: TOXENV=docs
    - python: '3.6'
      env: TOXENV=mypy
    - python: '2.7'
      env: TOXENV=flake8

install:
  - ( cd /opt && curl -sL https://github.com/jgm/pandoc/releases/download/2.1.2/pandoc-2.1.2-linux.tar.gz | tar -xzv --strip-components=1 pandoc-2.1.2/bin )
  - pip install -U tox codecov

before_script:
  - export PATH="/opt/bin:$PATH"

script:
  - tox -- -v

after_success:
  - if [[ -e .coverage ]]; then codecov -e $TOXENV; fi
